### ISSUE TITLE
Settings get cleared when ctrl+s is pressed repeatedly

### ISSUE THREAD

**Issue by jeppevinkel** [BOLL7708/desbot#14]
When saving multiple times rapidly using the `ctrl+s` keybind, the settings on the page can be cleared as a result.

I have only tested this on the `Speech` config page, and it can be reproduced by spamming the save keybind.

**Comment by BOLL7708** [comment]
c0ld also experienced this by double-clicking the save button, will have to get on this...

**Comment by BOLL7708** [comment]
It took a while, but this should be fixed in the next release.
